### ISSUE TITLE
jilla ls wont work

### ISSUE THREAD

**Issue by m19c** [juliangruber/jilla#19]
jilla ls
/usr/local/lib/node_modules/jilla/bin/jilla:141
        res.body.errorMessages.join('\n')
                              ^

TypeError: Cannot read property 'join' of undefined
    at /usr/local/lib/node_modules/jilla/bin/jilla:141:31
    at Request.callback (/usr/local/lib/node_modules/jilla/node_modules/superagent/lib/node/index.js:630:3)
    at Request.<anonymous> (/usr/local/lib/node_modules/jilla/node_modules/superagent/lib/node/index.js:131:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Stream.<anonymous> (/usr/local/lib/node_modules/jilla/node_modules/superagent/lib/node/index.js:773:12)
    at emitNone (events.js:72:20)
    at Stream.emit (events.js:166:7)
    at Unzip.<anonymous> (/usr/local/lib/node_modules/jilla/node_modules/superagent/lib/node/utils.js:124:12)
    at emitNone (events.js:72:20)

**Comment by Hesse** [comment]
Oddly, it use to work for me and now I'm seeing the same error:
.nvm/v0.12.4/lib/node_modules/jilla/bin/jilla:252
res.body.errorMessages.join('\n')

**Comment by Hesse** [comment]
I only see this error if I'm unable to connect (incorrect creds or otherwise). You probably want better error reporting/handling around this.

**Comment by rantoniuk** [comment]
+1

On invalid credentials:

```
root@2677b3ae070a:/# jilla ls
/usr/local/lib/node_modules/jilla/bin/jilla:141
        res.body.errorMessages.join('\n')
                              ^

TypeError: Cannot read property 'join' of undefined
    at /usr/local/lib/node_modules/jilla/bin/jilla:141:31
    at Request.callback (/usr/local/lib/node_modules/jilla/node_modules/superagent/lib/node/index.js:630:3)
    at Request.<anonymous> (/usr/local/lib/node_modules/jilla/node_modules/superagent/lib/node/index.js:131:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/jilla/node_modules/superagent/lib/node/index.js:773:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
```

On valid credentials:

```
root@2677b3ae070a:/# jilla ls
Error in the JQL Query: The character '@' is a reserved JQL character. You must enclose it in a string or use the escape '\u0040' instead. (line 1, character 20)
```
