### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by gurucubano** [juliangruber/jilla#21]
> I've installed 'node.js' 5.11.0 and jilla on my FreeBSD workstation. The
> configuration for the Jira URL, user and password went fine, but when I
> run the first real command it gives this error:
> 
> $ jilla ls
> events.js:154
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: unable to verify the first certificate
>     at Error (native)
>     at TLSSocket.<anonymous> (_tls_wrap.js:1065:38)
>     at emitNone (events.js:80:13)
>     at TLSSocket.emit (events.js:179:7)
>     at
> TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit
> (_tls_wrap.js:593:8)
>     at
> TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone
> (_tls_wrap.js:425:38)
> 
> a TCPDUMP shows that the Jira host gets contacted.
> Any idea how to fix this?
> 
> Thanks in advance

adding the following line makes it working:

/usr/local/lib/node_modules/jilla/bin/jilla*
**\* /usr/local/lib/node_modules/jilla/bin/jilla 2016-10-19 13:32:41.720559000 +0200
--- /usr/local/lib/node_modules/jilla/bin/jilla.orig    2016-10-19 13:59:00.785151000 +0200

---

**\* 16,23 ****
    db = _db;
    proxy = cfg.proxy || proxy;
    var cmd = process.argv[2];
-   // added by guru@unixarea.de, highly unsafe
-   process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
  switch (cmd) {
  case 'config':    return config();
  case 'ls':        return ls();
  --- 16,21 ----

What I would like to have added, for example, is setting 'storrypoints'.
Any plans to expand it?

```
matthias
```

**Comment by juliangruber** [comment]
Can you please make a pull request for your fix, and maybe open an issue for your desired new feature?

**Comment by gurucubano** [comment]
While I can create a new issue for the 'setting of storrypoints', I don't know how to make a pull request; I'm not so familiar with github.
