### ISSUE TITLE
Error executing ls command

### ISSUE THREAD

**Issue by pdaether** [juliangruber/jilla#6]
If i run `jila ls`i get an error about a **.**-sign in the jql.
The reason for this is a point in the username.

I can fix this in https://github.com/godmodelabs/jilla/blob/master/bin/jilla#L30 for example with `cfg.user.replace(/\./,'\\u002e')` but then i get another error:

```
/usr/lib/nodejs/jilla/bin/jilla:175
      if (cols[i][j].data.length > rowLengths[j]) {
                         ^
TypeError: Cannot read property 'length' of undefined
    at formatTable (/usr/lib/nodejs/jilla/bin/jilla:175:26)
    at /usr/lib/nodejs/jilla/bin/jilla:51:19
    at Request.callback (/usr/lib/nodejs/jilla/node_modules/superagent/lib/node/index.js:581:3)
    at Request.<anonymous> (/usr/lib/nodejs/jilla/node_modules/superagent/lib/node/index.js:133:10)
    at Request.EventEmitter.emit (events.js:96:17)
    at IncomingMessage.Request.end (/usr/lib/nodejs/jilla/node_modules/superagent/lib/node/index.js:710:12)
    at IncomingMessage.EventEmitter.emit (events.js:126:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
    at CleartextStream.socketOnData [as ondata] (http.js:1485:20)
```

The response looks good:

```
{ expand: 'schema,names',
  startAt: 0,
  maxResults: 50,
  total: 4,
  issues:
   [ { expand: 'editmeta,renderedFields,transitions,changelog,operations',
       id: '10485',
       self: 'https://domain/rest/api/2/issue/10485',
       key: 'KEY-74',
       fields: [Object] },
     { expand: 'editmeta,renderedFields,transitions,changelog,operations',
       id: '11603',
       self: 'https://domain/rest/api/2/issue/11603',
       key: 'KEY-150',
       fields: [Object] },
     { expand: 'editmeta,renderedFields,transitions,changelog,operations',
       id: '11208',
       self: 'https://domain/rest/api/2/issue/11208',
       key: 'KEY-123',
       fields: [Object] },
     { expand: 'editmeta,renderedFields,transitions,changelog,operations',
       id: '11707',
       self: 'https://domain/rest/api/2/issue/11707',
       key: 'KEY-155',
       fields: [Object] } ] }

```

I use a self-hosted jira v5.2.4, node v0.8.21

**Comment by ghost** [comment]
Try adding `return '';` to the bottom of the formatPrio() function.  Does that fix the issue?  I've just seen a similar problem with jilla search and this fixed it.

**Comment by ghost** [comment]
oh nm, it looks like commit a7737c2 fixed this.

**Comment by juliangruber** [comment]
if someone wants to come up with a testsuite...:D
